### ISSUE TITLE
smb_group provider has ruby syntax error

### ISSUE THREAD

**Issue by doksner** [kakwa/puppet-samba#19]
When I added smb_group to my manifest, I got the following error:

`Error: Could not autoload puppet/provider/smb_group/ruby: /var/lib/puppet/lib/puppet/provider/smb_group/ruby.rb:69: syntax error, unexpected kNOT, expecting kEND`

`return not(@add_entry or @modify_attr or @modify_group)`

It appears to work if I enclose everything after the `return` in an additional set of parentheses, but I don't REALLY know what I'm doing, so it's possible that it's not the complete solution.

**Comment by kakwa** [comment]
Can't reproduce, seems to be caused by old version of ruby found on legacy systems. Will not fix (I don't have the resources to test it)
