### ISSUE TITLE
krb5.conf.erb template: Detail: undefined local variable or method `realmuppercase'

### ISSUE THREAD

**Issue by ariacomputer** [kakwa/puppet-samba#21]
When using the krbconf, I'm receiving errors based on the krb5.conf.erb template:
`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Evaluation Error: Error while evaluating a Function Call, Failed to parse template samba/krb5.conf.erb:
  Filepath: /etc/puppetlabs/code/environments/development/modules/samba/templates/krb5.conf.erb
  Line: 12
  Detail: undefined local variable or method 'realmuppercase' for #<Puppet::Parser::TemplateWrapper:0x28ce7392>
 at /etc/puppetlabs/code/environments/development/modules/samba/manifests/classic.pp:103:18 on node testbed.eorzea.lan
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run`

Changing realmuppercase and realmlowercase in krb5.conf.erb to @realmuppercase and @realmlowercase seems to fix the issue.  

Is this an error?  If so, I can create a pull request to fix the template.

**Comment by pjmorr** [comment]
Thats the same change i made this morning to a local copy.  beat me to the punch. ;)

**Comment by kakwa** [comment]
Thank you, uploaded to puppet forge in version 0.7.1
