### ISSUE TITLE
"Could not find dependent Service[SambaWinBind]" if manage_winbind == false

### ISSUE THREAD

**Issue by fkleon** [kakwa/puppet-samba#26]
Configuring `samba::classic` to not manage winbind leads to errors about a missing `SambaWinBind` service definition.

``` puppet
class { '::samba::classic':
[...]
  join_domain    => true,
  manage_winbind => false,
[...]
}
```

results in

```
Error: Could not find dependent Service[SambaWinBind] for File[/etc/krb5.conf] at /vagrant/puppet/vendor/samba/manifests/classic.pp:103
```

and subsequently

```
Error: Could not find dependent Service[SambaWinBind] for Samba::Option[[global]idmap config * : backend] at /vagrant/puppet/vendor/samba/manifests/idmap.pp:155
```

After a quick scan of the sources I can see two possible solutions:
- check that the service has been defined outside the module when validating the `samba::classic` parameters, and print some helpful message if that is not the case.
- dynamically adapt the `notify` and `require` statements to exclude the winbind service (however, it's probably actually required for stuff to work?).

I've prepared a pull request for the first option, as I don't understand enough of how Samba services work together to determine whether option 2 is actually going to work.

**Comment by kakwa** [comment]
Winbind is optional, it's a daemon meant to recover users and their ID from Active Directory (and optionally maintains a mapping DB between Unix UID and Windows SID (idmap)).

The second option seems more appropriate.

Thank you for reporting the bug

**Comment by kakwa** [comment]
fixed by https://github.com/kakwa/puppet-samba/commit/388767085d69f7fbf70642f2f74e9c7a5382afc4
