### ISSUE TITLE
libnss-winbind

### ISSUE THREAD

**Issue by night199uk** [kakwa/puppet-samba#30]
When provisioning a member server?
1) On Ubuntu libnss-winbind is required for nsswitch for winbind. Should it be installed if $nsswitch = true?
2) Should this module also set winbind for shadow in nsswitch.conf?
3) Any support for provisioning authentication with pam_winbind along with auth-client-config, pam-auth-config, etc?

**Comment by kakwa** [comment]
1) indeed, the libnss-winbind is missing, It's a mistake on my part, it should be installed on Debian derivatives if nsswitch is set to true.

2) and 3. I provide minimal nsswitch integration for simple use cases. The main goal is to be able to resolve users uid and groups to set permissions on the shares (through user/group ownership and ACLs). The goal is not to provide authentication on the server (through ssh for example).

For more complex setups I would recommend disabling the nsswitch setup of this module and using dedicated modules:
* https://forge.puppet.com/trlinkin/nsswitch
* https://forge.puppet.com/ghoneycutt/pam

I've never tried it however.

**Comment by night199uk** [comment]
Well, I opened PRs for 1, and 2 & 3 together as I needed this functionality to work in a slick way... This Samba module was already a lot better than some of the standalone winbind puppet modules I tried. :-) Hope you can consider them.

I have a couple more suggestions:
It would be nice to be able to enable the winbind module without necessarily installing the samba package for a domain joined server without sharing. I'm thinking about adding a $sharing = true|false flag (default true) on the ::classic option.   If $sharing == true, samba (smbd) will be installed; otherwise we just install winbind and the peripheral services (nsswitch & pam).

Also, suggest we could break out the ::classic to more accurately reflect the roles in which samba could be deployed. A true classic server has no DC, domain join, or REALM, right? So you'd end up with:
::dc
::member - domain joined AD member (current classic with this and the PAM PR)
::standalone - simplified version of current classic - remove REALM and other required parameters. A true standalone Samba file share. 

However this would be a breaking change for folks currently using the '::classic' option. We could retain the existing ::classic for compatibility. What do you think - would you consider PRs for this?
