### ISSUE TITLE
Puppet run changes selinux context of directory / share

### ISSUE THREAD

**Issue by monotek** [kakwa/puppet-samba#33]
I use Centos 7.3.
Every puppet run changes the selinux context of my directory like:

`Notice: /Stage[main]/Main/Node[centos]/Samba::Share[Archive]/Samba::Dir[/backup/Archive]/File[/backup/Archive]/seltype: seltype changed 'samba_share_t' to 'default_t'
`

To get it work again i have to:

`chcon -v -t samba_share_t /backup/Archive`

But its disabled by  the next puppet run again and therefore the share does not work anymore.

The share looks like:

```
  ::samba::share { 'Archive':
    path             => '/backup/Archive',
    manage_directory => true,        # * let the resource handle the shared
    owner            => 'tim',      # * owner of the share directory
    group            => 'tim',      # * group of the share directory
    mode             => '0770',      # * mode of the share directory
    #acl              => 'samba_share_t',
    #seltype          => 'samba_share_t',
    options          => {            # * Custom options in section [Test Share]
      'wide links'     => 'no',
      'writeable'      => 'yes',
      'browsable'      => 'yes',
      'force user'     => 'archive',
      'force group'    => 'archive',
      'public'         => 'yes',
      'create mode'    => '660',
      'directory mode' => '770',
      'guest ok'       => 'No',
      'valid users'    => 'archive',
    },
  }
```

**Comment by kakwa** [comment]
I would suggest setting ```manage_directory => false,``` and managing the directory directly by the file puppet resource. It's for this kind of unforeseen usage that this switch exists.

Something like:
```puppet
  ::samba::share { 'Archive':
    path             => '/backup/Archive',
    manage_directory => false,       
    options          => {            # * Custom options in section [Test Share]
      'wide links'     => 'no',
      'writeable'      => 'yes',
      'browsable'      => 'yes',
      'force user'     => 'archive',
      'force group'    => 'archive',
      'public'         => 'yes',
      'create mode'    => '660',
      'directory mode' => '770',
      'guest ok'       => 'No',
      'valid users'    => 'archive',
    },
  }

file {'/backup/Archive':
    ensure  => directory,
    owner   => 'tim',
    group   => 'tim',
    mode    => '0770',
    seltype  => 'samba_share_t',
}
```

Generally, what I tried to do in this module is to have some unified and coherent management of resources, but to have switches to disable this unified management for the many unforeseen use cases.

However, one thing that could be interesting is to expose the raw parameters of the file resource using this synthax:
https://docs.puppet.com/puppet/4.9/lang_resources_advanced.html#setting-attributes-from-a-hash

I've done it in the EXPOSE_FILE_PARAM branch:
https://github.com/kakwa/puppet-samba/commit/aa0c402d0893dabe79f6c3fe73e9ac624404858a

However, this '*' syntax seems only supported for Puppet version >4, implementing it this way would mean dropping support for older versions of Puppet, including the versions used by Debian stable.
