### ISSUE TITLE
Clean smb.conf from old values

### ISSUE THREAD

**Issue by monotek** [kakwa/puppet-samba#35]
Is there a possibility to clean the smb.conf from all values?
I only wan't to have values in it which are defined in the module.

**Comment by kakwa** [comment]
It should be the case, at least in theory, with classic and dc class.
https://github.com/kakwa/puppet-samba/blob/453f96ca39e79cbcb98083efa5b1e10946fdb5a9/manifests/classic.pp#L319
https://github.com/kakwa/puppet-samba/blob/master/manifests/dc.pp#L423

Will check at home

**Comment by monotek** [comment]
No, on my Centos 7.3 there are leftovers (printers for example) from the smb.conf which is installed by the package.
As workaround i did an "echo "" > smb.conf;puppet agent -tv".

**Comment by kakwa** [comment]
I've done some testing, cannot reproduce:

Notice: /Stage[main]/Samba::Classic/Smb_setting[global/not_existant_parameter_1]/ensure: removed
Notice: /Stage[main]/Samba::Classic/Smb_setting[global/not_existant_parameter_2]/ensure: removed
Notice: /Stage[main]/Samba::Classic/Smb_setting[Test Share/not_existant_parameter_3]/ensure: removed

However, please note that the comments (and commented parameters/shares) will not be removed
