### ISSUE TITLE
Puppet 4 support

### ISSUE THREAD

**Issue by benh57** [kakwa/puppet-samba#40]
This module gives many warnings with the latest puppet + stdlib.

Puppet 3.x is EOL as of 2016, it's time to convert over to Puppet 4. All validate_ calls should be moved to type definitions instead.
`==> Warning: This method is deprecated, please use match expressions with Stdlib::Compat::Bool instead. They are described at https://docs.puppet.com/puppet/latest/reference/lang_data_type.html#match-expressions. at ["..../samba/manifests/params.pp", 6]`

(and more...)

Good guide:
https://voxpupuli.org/blog/2017/01/11/migrating-to-puppet4/

**Comment by kakwa** [comment]
As long as it's only warnings, I will keep it that way for now.

The reason being that many "stable" distributions still ship Puppet 3.x (Debian Jessie, CentOS 7 (via Epel)).

**Comment by benh57** [comment]
Puppet strongly recommends not using distro versions of Puppet.

It's actually possible to remove the stdlib warnings by using the validate_legacy call. I can submit a PR for that if you like.

**Comment by kakwa** [comment]
Well, every upstreams will push for using the latest version they release. In the end if it was really done, we would basically have Debian Experimental/Arch/Gentoo or any other rolling release distribution in production. 😉 

validate_legacy might be interesting, give me a few days to read the documentation/play with it.

**Comment by benh57** [comment]
sounds like EPEL strongly prefers never to do major incompatible version updates. Puppet 4 is a new package though (puppet-agent), so it could in theory be added as a new package.

As i mentioned though, no one uses EPEL for puppet.
