### ISSUE TITLE
What's the purpose of file resources /etc/samba and /etc/samba/smb_path?

### ISSUE THREAD

**Issue by bschonec** [kakwa/puppet-samba#56]
Since the (red hat/centos) package samba-common already provides for creating /etc/samba and setting permissions appropriately, what's the purpose of defining /etc/samba/smb_path as a file resource?

https://github.com/kakwa/puppet-samba/blob/7ce3dd40bfc667a697151d9e79ba6e2982160db5/manifests/classic.pp#L98

**Comment by kakwa** [comment]
It's necessary for the lib used to managed individual settings in the smb.conf file (basically an ini file):

 https://github.com/kakwa/puppet-samba/blob/master/lib/puppet/provider/smb_setting/ruby.rb#L16

Keep in mind that on some systems, the configuration path is not /etc/samba/smb.conf (for example, FreeBSD where it's in /usr/locale/etc/samba/smb.conf), it could also be useful with custom made packages with configuration in /opt/<something>/etc for example.

It's not a very satisfying solution as it needs 2 iterations of application to work properly, but it works in the end.

**Comment by bschonec** [comment]
I understand your explanation but I'd argue that you don't need the file resource at all.  No matter what platform/flavor of Linux/FreeBSD you use, the smb.conf file will be created by the OS's package management system.  Yes, you need to define the path to the smb.conf file so that you can manage the parameters in the smb.conf file (augeas?) but you don't need to define that file as a resource in Puppet.  It's already created by the package manager.

**Comment by kakwa** [comment]
The */etc/samba/* directory doesn't necessarily exists or is created by the samba package of <PICK DISTRIBUTION>.

Typically FreeBSD has the configuration file at */usr/local/etc/smb4.conf* and no ".*/etc/samba/" directory is created.

Also, the "/etc/samba/smb_path" is hard coded inside the provider (not very elegant, I know), so it's necessary to create the '/etc/samba/' dir and then the file '/etc/samba/smb_path'.

This file necessary to make the path to smb.conf configurable in the smb_setting provider.
And the provider needs to know the configuration file path for `puppet resource smb_setting` and  `purge => true,` (https://github.com/kakwa/puppet-samba/blob/master/manifests/classic.pp#L316) to work.

The provider is implemented here:
https://github.com/kakwa/puppet-samba/blob/master/lib/puppet/provider/smb_setting/ruby.rb

Also, this provider is not based on augeas, it's derived from the ini puppet module.
