### ISSUE TITLE
Error configuring DC

### ISSUE THREAD

**Issue by luiszandonadi** [kakwa/puppet-samba#7]
this error appears on configure dc controller, can help me?

```
err: Failed to apply catalog: Parameter name failed on Resources[smb_setting]: Could not find resource type 'smb_setting' at /etc/puppet/modules/samba/manifests/dc.pp:385
```

**Comment by kakwa** [comment]
This part of the code is meant to clean smb.conf by removing undeclared params.

It's a wild guess but did you set pluginsync = true on the agent?

Is your smb.conf path is "/etc/samba/smb.conf" or something different? There is some "not so clean" code in the provider, but in theory it should run fine the second time you apply (once /etc/samba/smb_path is deployed).

Could you tell me more about your environment (puppet versions on agent and master, Linux distribution, samba version).

**Comment by luiszandonadi** [comment]
Thanks Pierre,

I'm using 3.8.3 puppet both the server and the prowling agent in Debian
Wheezy x64, I tried inserting the autosyn = true flag on the agent as
recommended and apparently the problem was solved. But yet there was a new
problem regarding the samba-tool and not applying the settings:

```
rr: / Stage [main] / Samba :: Dc / Exec [provisionAD] / returns: change
from 0 to NotRun failed: sh: 1: / usr / bin / samba-tool: not found
```

A curious fact is that repeated the same procedure in Debian 8 x64 and
everything was fine.

Thank you for your help!

Atenciosamente,

_Luis Zandonadi Bissoli_
(28) 99948-3131

2015-10-15 3:24 GMT-03:00 Carpentier Pierre-Francois <
notifications@github.com>:

**Comment by kakwa** [comment]
Samba starts to implement domain controller features in version > 4.0.0. In wheezy, the samba package is 3.6.6, so no DC feature.
However, it's possible to install samba 4 on wheezy using the sernet package or getting samba from wheezy-backports.

The samba classic class should work.
