### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by luiszandonadi** [kakwa/puppet-samba#8]
It would be interesting if you could create examples of more complex configurations, showing how to use ACL and other common cases.

**Comment by kakwa** [comment]
I've created small examples:

https://github.com/kakwa/puppet-samba/tree/master/examples

It shows how to deploy a domain controller and a share authenticating on it.

No ACL for now (I don't have a configuration using them at hand right now), I will try to provide an example in a few days.

I'm not the biggest samba expert by far (samba has many parameters, and doesn't have the must helpful error messages I've ever seen...). 
However, I've tried to add ways to manage parameters not handled directly by this module, letting module users customize and tune their deployment (options/globaloptions parameters for example).

If anyone has more complex examples (usual tuning options, idmap configs, interesting permission management on shares...) I would happily take them and put them here ^^.
